[package]
name = "ui_p7_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
env_logger = "0.11"
log = "0.4"
p7 = { path = "../../radiance/p7lang/p7" }
radiance = { path = "../../radiance/radiance" }
