name: Linux CI Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          rustflags: ''
      - name: Install Deps
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/lunarg.gpg
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt update
          sudo apt install nasm vulkan-sdk libudev-dev
      - name: Cache ffmpeg
        uses: actions/cache@v3
        with:
          path: vcpkg_installed
          key: ${{ runner.os }}-build-ffmpeg
      - name: Install ffmpeg
        run: |
          vcpkg install --triplet=x64-linux
      - name: Build
        run: cargo build --workspace --release --verbose
      - name: AppImage Packaging
        run: |
          cd target
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          ./linuxdeploy-x86_64.AppImage --appdir AppDir
          cp ../packaging/AppImage/* ./AppDir/
          cp ./release/yaobow ./AppDir/usr/bin/
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage
      - uses: actions/upload-artifact@v4
        with:
          name: yaobow-AppImage
          path: target/yaobow*.AppImage
