name: macOS CI Build

on:
  push:
    branches: [debug_macos]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-build:
    runs-on: macos-latest
    env:
      VCPKG_FEATURE_FLAGS: manifests
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          rustflags: ''
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - name: Install Deps
        run: |
          brew install nasm molten-vk vulkan-headers vulkan-loader shaderc
      - name: Cache ffmpeg
        uses: actions/cache@v3
        with:
          path: vcpkg_installed
          key: ${{ runner.os }}-build-ffmpeg
      - name: Install ffmpeg
        run: |
          vcpkg install --triplet=arm64-osx
      - name: Build
        run: cargo build --workspace --release --verbose
